development:
  adapter: postgresql
  encoding: unicode
  database: candy_development
  pool: 5
  username: jwo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: candy_test
  pool: 5
  username: jwo
  password:
